### ISSUE TITLE
Set Up Kubernetes for Orchestration

### ISSUE THREAD

**Issue by Startonix** [Startonix/ModularAI-#16]
Deploy and manage containers using Kubernetes for scalability and resilience.
   - Example: Kubernetes deployment configuration.

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: nlp-service
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nlp-service
     template:
       metadata:
         labels:
           app: nlp-service
       spec:
         containers:
         - name: nlp-service
           image: your-docker-image
           ports:
           - containerPort: 80
   ```
