### ISSUE TITLE
Set Up CI/CD Pipeline

### ISSUE THREAD

**Issue by Startonix** [Startonix/ModularAI-#20]
Use CI/CD tools like Jenkins, GitLab CI, or GitHub Actions to automate testing and deployment.
   - Example: Basic CI/CD pipeline with GitHub Actions.

   ```yaml
   name: CI/CD Pipeline

   on: [push]

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: 3.8
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run tests
         run: |
           python -m unittest discover
   ```
