### ISSUE TITLE
Orchestration with Kubernetes

### ISSUE THREAD

**Issue by Startonix** [Startonix/ModularAI-#9]
Deploy and manage containers using Kubernetes for scalability and resilience.
   - Example: `kubernetes_deployment.yaml`
     ```yaml
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: chatgpt-service
     spec:
       replicas: 3
       selector:
         matchLabels:
           app: chatgpt-service
       template:
         metadata:
           labels:
             app: chatgpt-service
         spec:
           containers:
           - name: chatgpt-service
             image: your-docker-image
             ports:
             - containerPort: 80
     ```
